This notebook is used to get the appropriate audio file names from Audioset's and FSD50k's training and evaluation sets that correspond to a given mid (Machine identifier) list. This list of filenames can then be used to construct appropriate dataset specific training and evaluation sets for further downstream machine learning.

In [2]:
import utility_funcs as my_util

In [3]:
# Get the list of desired mids
mids = my_util.pickle_load("top_50_mids.pckl")
mids

{'/m/012f08',
 '/m/014zdl',
 '/m/015lz1',
 '/m/01b_21',
 '/m/01h8n0',
 '/m/01j3sz',
 '/m/020bb7',
 '/m/028ght',
 '/m/02rtxlg',
 '/m/02zsn',
 '/m/032s66',
 '/m/0395lw',
 '/m/03m9d0z',
 '/m/03qc9zr',
 '/m/03qtwd',
 '/m/03vt0',
 '/m/04rlf',
 '/m/053hz1',
 '/m/05tny_',
 '/m/05zppz',
 '/m/07jdr',
 '/m/07p6fty',
 '/m/07pbtc8',
 '/m/07pggtn',
 '/m/07pp_mv',
 '/m/07q2z82',
 '/m/07qcpgn',
 '/m/07qjznt',
 '/m/07qnq_y',
 '/m/07r04',
 '/m/07r660_',
 '/m/07rrlb6',
 '/m/07s0dtb',
 '/m/0838f',
 '/m/0912c9',
 '/m/09l8g',
 '/m/09x0r',
 '/m/09xqv',
 '/m/0brhx',
 '/m/0bt9lr',
 '/m/0btp2',
 '/m/0jbk',
 '/m/0k4j',
 '/m/0l15bq',
 '/m/0lyf6',
 '/m/0ytgt',
 '/t/dd00003',
 '/t/dd00004',
 '/t/dd00077',
 '/t/dd00112'}

In [4]:


# Load in the respective metafiles for both audioset and fsd50k, keeping only relevant columns
PATH_TO_AS_TRAIN = r'C:\Users\mp431591\Documents\audioset_label_files\audioset_train_strong.tsv'
PATH_TO_AS_EVAL = r'C:\Users\mp431591\Documents\audioset_label_files\audioset_eval_strong.tsv'

PATH_TO_FSD_TRAIN = r'C:\Users\mp431591\Documents\FSD50k_label_files\dev.csv' # dev == train
PATH_TO_FSD_EVAL = r'C:\Users\mp431591\Documents\FSD50k_label_files\eval.csv'

audioset_train_meta = my_util.read_strong_audioset_metatable(PATH_TO_AS_TRAIN)
audioset_eval_meta = my_util.read_strong_audioset_metatable(PATH_TO_AS_EVAL)

fsd50k_train_meta = my_util.read_fsd50k_metatable(PATH_TO_FSD_TRAIN)
fsd50k_eval_meta = my_util.read_fsd50k_metatable(PATH_TO_FSD_EVAL)

In [5]:
audioset_train_filenames = my_util.get_valid_audioset_filenames_for_mids(audioset_train_meta, mids=mids)
print(f"Number of valid files for audioset train: {len(audioset_train_filenames)}")

Number of valid files for audioset train: 93370

In [6]:
audioset_eval_filenames = my_util.get_valid_audioset_filenames_for_mids(audioset_eval_meta, mids=mids)
print(f"Number of valid files for audioset eval: {len(audioset_eval_filenames)}")

Number of valid files for audioset eval: 15276

In [7]:
fsd50k_train_meta.head()

   fname                                           mids
0  64760  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
1  16399  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
2  16401  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
3  16402  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
4  16404  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf

In [8]:
# Explode the fsd50k table to make checking for valid rows easier
fsd50k_train_meta_exploded = (fsd50k_train_meta.set_index(["fname"])
                              .apply(lambda x: x.str.split(',')
                                     .explode())
                                     .reset_index())
fsd50k_train_meta_exploded.head(10)

   fname       mids
0  64760   /m/02sgy
1  64760   /m/0342h
2  64760  /m/0fx80y
3  64760   /m/04szw
4  64760   /m/04rlf
5  16399   /m/02sgy
6  16399   /m/0342h
7  16399  /m/0fx80y
8  16399   /m/04szw
9  16399   /m/04rlf

In [ ]:
fsd50k_train_filenames = my_util.get_valid_fsd50k_filenames_for_mids(fsd50k_train_meta_exploded, mids)
print(f"Number of valid FSD50k train filenames: {len(fsd50k_train_filenames)}")

NUmber of valid FSD50k train filenames: 29920

In [11]:
fsd50k_eval_meta_exploded = (fsd50k_eval_meta.set_index(["fname"])
                              .apply(lambda x: x.str.split(',')
                                     .explode())
                                     .reset_index())
fsd50k_eval_meta_exploded.head(10)

    fname       mids
0   37199   /m/02sgy
1   37199   /m/0342h
2   37199  /m/0fx80y
3   37199   /m/04szw
4   37199   /m/04rlf
5  175151   /m/02sgy
6  175151   /m/0342h
7  175151  /m/0fx80y
8  175151   /m/04szw
9  175151   /m/04rlf

In [ ]:
fsd50k_eval_filenames = my_util.get_valid_fsd50k_filenames_for_mids(fsd50k_eval_meta_exploded, mids)
print(f"Number of valid FSD50k eval filenames: {len(fsd50k_eval_filenames)}")

Number of valid FSD50k train filenames: 7373